#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#logout:
#    path: /
#    controller: App\Controller\MenuController::logoutAction

# config/routes.yaml

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /administrator

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /administrator

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /administrator/resetting

# añadidas 11-4-2018
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administrator

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administrator

# Redireccionar la página de inicio
# redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /principalescentrosturisticos
        permanent: true

# ******************           
alemail:
    path: /ar/{regionSlug}/{provinceSlug}/{localitySlug}/alojamiento
       
